### ISSUE TITLE
1.5.10: function 'log_no_irk_for_peer' was not declared

### ISSUE THREAD

**Issue by iphoting** [DerekSeaman/irk-capture#16]
Got the following error when compiling 1.5.10:

`src/esphome/components/irk_capture/irk_capture.cpp: In function 'int esphome::irk_capture::handle_gap_disconnect(IRKCaptureComponent*, ble_gap_event*)':
src/esphome/components/irk_capture/irk_capture.cpp:1078:5: error: 'log_no_irk_for_peer' was not declared in this scope
 1078 |     log_no_irk_for_peer(d.peer_id_addr);
      |     ^~~~~~~~~~~~~~~~~~~
*** [.pioenvs/irk-capture-c6/src/esphome/components/irk_capture/irk_capture.cpp.o] Error 1 `

**Comment by 16-9** [comment]
Confirm the issue when recompiling my yaml with ESPHome 2026.4.3

**Comment by DerekSeaman** [comment]
I'm on it guys...give me a few hours so I can get to it.

**Comment by DerekSeaman** [comment]
Fixed in 1.5.11. Clean the build cache and try again.

**Comment by 16-9** [comment]
Thanks, Derek. I confirmed the issue is gone. Was able to compile with ESPHome 2026.4.3
